"""External catalogues (e.g. NVIDIA/skills): sync snapshots and curated reviews.

Each catalogue lives in catalogs/<name>/:
  source.json   — human-owned: upstream repo, file to look for, family prefixes
  catalog.json  — generated by `rnd catalog sync <name>`; never hand-edit
  review.json   — human-owned: studio fit + notes per family and per item
"""

import base64
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from . import frontmatter

FITS = ("direct", "adjacent", "general")
BATCH = 40


class CatalogError(RuntimeError):
    def __init__(self, code, message, hint=""):
        super().__init__(message)
        self.code, self.hint = code, hint


def catalog_dirs(root):
    base = Path(root) / "catalogs"
    if not base.is_dir():
        return []
    return sorted(d for d in base.iterdir() if (d / "source.json").is_file())


def _read_json(path, default=None):
    if not path.is_file():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def family_of(name, prefixes):
    best = ""
    for p in prefixes:
        if (name == p or name.startswith(p + "-")) and len(p) > len(best):
            best = p
    return best or name.split("-", 1)[0]


def load(cat_dir):
    """Return (catalog_meta, items, problems) with review fit merged in."""
    source = _read_json(cat_dir / "source.json", {})
    snap = _read_json(cat_dir / "catalog.json")
    review = _read_json(cat_dir / "review.json", {}) or {}
    problems = []
    if snap is None:
        return None, [], [f"catalogs/{cat_dir.name}: no catalog.json yet — run `rnd catalog sync {cat_dir.name}`"]
    fam_review = review.get("families", {})
    item_review = review.get("items", {})
    names = {it["name"] for it in snap.get("items", [])}
    for label, table in (("family", fam_review), ("item", item_review)):
        for key, val in table.items():
            if val.get("fit") not in FITS:
                problems.append(f"catalogs/{cat_dir.name}/review.json: {label} {key!r} fit must be one of {', '.join(FITS)}")
    for key in item_review:
        if key not in names:
            problems.append(f"catalogs/{cat_dir.name}/review.json: item {key!r} is not in the snapshot")
    items = []
    for it in snap.get("items", []):
        fam = fam_review.get(it["family"], {})
        own = item_review.get(it["name"], {})
        items.append({**it,
                      "fit": own.get("fit") or fam.get("fit") or "",
                      "note": own.get("note") or "",
                      "family_note": fam.get("note") or ""})
    meta = {"name": cat_dir.name, "title": source.get("title", cat_dir.name),
            "upstream": snap.get("upstream", ""), "ref": snap.get("ref", ""),
            "synced_at": snap.get("synced_at", ""), "license": snap.get("license", ""),
            "count": len(items), "lanes": snap.get("lanes", [])}
    return meta, items, problems


def _gh(args):
    try:
        res = subprocess.run(["gh", *args], capture_output=True, text=True, encoding="utf-8")
    except FileNotFoundError:
        raise CatalogError("GH_MISSING", "the GitHub CLI 'gh' is not on PATH",
                           "install gh and run `gh auth login`")
    if res.returncode != 0:
        raise CatalogError("GH_FAILED", f"gh {' '.join(args[:2])} failed: {res.stderr.strip()[:300]}",
                           "check `gh auth status` and network access")
    return res.stdout


def sync(root, name, log=print):
    cat_dir = Path(root) / "catalogs" / name
    source = _read_json(cat_dir / "source.json")
    if source is None:
        raise CatalogError("CATALOG_UNKNOWN", f"no catalogs/{name}/source.json",
                           "create source.json with 'repo' and 'match' first")
    repo, match = source["repo"], source.get("match", "SKILL.md")
    owner, repo_name = repo.split("/", 1)
    info = json.loads(_gh(["api", f"repos/{repo}"]))
    tree = json.loads(_gh(["api", f"repos/{repo}/git/trees/HEAD?recursive=1"]))
    sha = tree["sha"]
    paths = [t["path"] for t in tree["tree"] if t["path"].endswith("/" + match)]
    log(f"{repo}@{sha[:12]}: {len(paths)} {match} files")

    texts = {}
    for start in range(0, len(paths), BATCH):
        chunk = paths[start:start + BATCH]
        fields = " ".join(
            f'f{n}: object(expression: {json.dumps(sha + ":" + p)}) {{ ... on Blob {{ text byteSize }} }}'
            for n, p in enumerate(chunk))
        query = f"query {{ repository(owner: {json.dumps(owner)}, name: {json.dumps(repo_name)}) {{ {fields} }} }}"
        data = json.loads(_gh(["api", "graphql", "-f", f"query={query}"]))["data"]["repository"]
        for n, p in enumerate(chunk):
            blob = data.get(f"f{n}") or {}
            texts[p] = (blob.get("text") or "", blob.get("byteSize") or 0)
        log(f"  fetched {min(start + BATCH, len(paths))}/{len(paths)}")

    lanes, lane_of = [], {}
    if source.get("groupings_file"):
        content = json.loads(_gh(["api", f"repos/{repo}/contents/{source['groupings_file']}?ref={sha}"]))
        groupings = json.loads(base64.b64decode(content["content"]).decode("utf-8"))
        for g in groupings.get("groupings", []):
            lanes.append({"title": g["title"], "description": g.get("description", ""),
                          "count": len(g.get("skills", []))})
            for s in g.get("skills", []):
                lane_of.setdefault(s, []).append(g["title"])
        log(f"{source['groupings_file']}: {len(lanes)} lanes")

    prefixes = source.get("families", [])
    preferred = source.get("prefer_prefix", "")
    items, unparsed = {}, []
    for p in sorted(paths):
        text, size = texts.get(p, ("", 0))
        try:
            meta, _ = frontmatter.read(text)
        except frontmatter.FrontmatterError as exc:
            meta = {}
            unparsed.append(f"{p}: {exc}")
        folder = p.rsplit("/", 2)[-2]
        skill = str(meta.get("name") or folder)
        if skill in items and not (preferred and p.startswith(preferred)):
            continue
        description = meta.get("description") or ""
        items[skill] = {
            "name": skill,
            # The folder name carries the product prefix even when the
            # declared name is shorter (bionemo-kermt-* declares kermt-*).
            "family": family_of(folder, prefixes),
            "lanes": lane_of.get(skill) or lane_of.get(folder) or [],
            "description": " ".join(str(description).split()),
            "license": str(meta.get("license") or ""),
            "path": p,
            "bytes": size,
            "url": f"https://github.com/{repo}/blob/{sha}/{p}",
        }
    snapshot = {
        "upstream": f"https://github.com/{repo}",
        "ref": sha,
        "synced_at": datetime.now(timezone.utc).replace(microsecond=0).isoformat(),
        "license": (info.get("license") or {}).get("spdx_id", ""),
        "unparsed": unparsed,
        "lanes": lanes,
        "items": sorted(items.values(), key=lambda it: it["name"]),
    }
    (cat_dir / "catalog.json").write_text(json.dumps(snapshot, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    log(f"wrote catalogs/{name}/catalog.json: {len(items)} items, {len(unparsed)} unparsed")
    return snapshot
